### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by buhuizuodanb** [Shengqi77/UG2_Turbulence_Mitigation#1]
你好，可以分享一下2.2的数据集吗，万分感谢

**Comment by Shengqi77** [comment]
你好，去年湍流校正赛道的所有数据集（dry-run、final test）在这个网站：
https://cvpr2023.ug2challenge.org/dataset23_t2.html
今年赛道的数据集在下面这个网站：
https://cvpr2024ug2challenge.github.io/dataset24_t2.html
